#!/usr/bin/env python
"""\
test_template

A sample unit test file.
"""

__author__   = 'John Shamo'
__revision__ = "$Id: test_template,v 1.1 2002/11/28 00:49:56 myers_carpenter Exp $"

import unittest

class SampleTestCase(unittest.TestCase):
    def setUp(self):
        pass

    def tearDown(self):
	pass

    def testSample1(self):
	pass 

    def testResize(self):
	pass



def suite():
    suite = unittest.makeSuite(SampleTestCase, 'test')

    # suite2 = module2.TheTestSuite()
    # return unittest.TestSuite((suite1, suite2))

    return suite

if __name__ == "__main__":
    unittest.main()
